apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    deployment: terraform
    dominion: {{DOMINION}}
    environment: {{ENVIRONMENT}}
    owner: {{OWNER}}
    prefix: ""
    subdominion: {{SUBDOMINION}}
    version_name: {{VERSION_NAME}}
  name: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-pdb
  namespace: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-namespace
spec:
  minAvailable: {{MIN_PODS}}
  selector:
    matchLabels:
      deployment: terraform
      dominion: {{DOMINION}}
      environment: {{ENVIRONMENT}}
      owner: {{OWNER}}
      prefix: ""
      subdominion: {{SUBDOMINION}}
      version_name: {{VERSION_NAME}}
