apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    deployment: terraform
    dominion: {{DOMINION}}
    environment: {{ENVIRONMENT}}
    owner: {{OWNER}}
    subdominion: {{SUBDOMINION}}
    version_name: {{VERSION_NAME}}
  name: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-k8srole
  namespace: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-namespace
rules:
- apiGroups:
  - ""
  resourceNames:
  - ""
  resources:
  - ""
  verbs:
  - ""
