apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: terraform
    dominion: {{DOMINION}}
    environment: {{ENVIRONMENT}}
    owner: {{OWNER}}
    prefix: ""
    subdominion: {{SUBDOMINION}}
    version_name: {{VERSION_NAME}}
  name: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-service
  namespace: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-namespace
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{CONTAINER_PORT}}
  selector:
    deployment: terraform
    dominion: {{DOMINION}}
    environment: {{ENVIRONMENT}}
    owner: {{OWNER}}
    prefix: ""
    subdominion: {{SUBDOMINION}}
    version_name: {{VERSION_NAME}}
  sessionAffinity: None
  type: NodePort
