apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::847574585735:role/{{APP_ENV}}-{{DOMINION}}-{{SUBDOMINION}}
  creationTimestamp: "2021-07-21T15:40:18Z"
  name: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-service-account
  namespace: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-namespace
secrets:
- name: {{ENVIRONMENT}}-{{DOMINION}}-{{SUBDOMINION}}-{{VERSION_NAME}}-service-account-token
